before_script:
 - apt-get update --yes
 - apt-get install --yes python cmake

build-cppl:
  stage: build
  script:
    - echo Number of CPU cores $(grep -c ^processor /proc/cpuinfo)
    - mkdir cppl.build
    - cd cppl.build
    - cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX=$PWD/install -G "Unix Makefiles" ../llvm
    - make -j$(( $(grep -c ^processor /proc/cpuinfo)*2 )) install
  only:
    - levitation-draft

test-cppl:
  stage: test
  script:
    - make -j$(( $(grep -c ^processor /proc/cpuinfo)*2 )) check-clang
  only:
    - levitation-draft
