before_script:
 - apt-get update --yes
 - apt-get install --yes python cmake

build-cppl:
  stage: build
  script:
    - mkdir cppl.build
    - cd cppl.build
    - cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX=$PWD/install -G "Unix Makefiles" ../llvm
    - make install
  only:
    - levitation-draft

test-cppl:
  stage: test
  script:
    - make check-clang
  only:
    - levitation-draft