name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          # - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          # - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++", release_name: "cppl-linux-x86_64" }
          - { name: "MacOS clang", os: macos-10.15, cc: "clang", cxx: "clang++", release_name: "cppl-darwin-x86_64" }
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        # ninja version to download. Default: 1.10.0
        version: 1.10.0
    - name: CMake
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=${{ runner.workspace }}/${{ matrix.config.release_name }} \
              -DLLVM_ENABLE_PROJECTS="clang;cppl" \
              -G "Ninja" ${{ runner.workspace }}/cppl/llvm
    - name: Sources Archive 
      run: |
        tar pczf \
            ${{ runner.workspace }}/${{ matrix.config.release_name }}-src.tgz \
            -C ${{ runner.workspace }} cppl
    - name: Upload Source Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{ matrix.config.release_name }}-src
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ runner.workspace }}/${{ matrix.config.release_name }}-src.tgz
            
    - name: Build
      run: ninja -j4 clang
    - name: Check
      run: ninja -j4 check-clang
    - name: Install
      run: ninja -j4 install-clang
      
    - name: Archive 
      run: |
        tar pczf \
            ${{ runner.workspace }}/${{ matrix.config.release_name }}.tgz \
            -C ${{ runner.workspace }} ${{ matrix.config.release_name }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{ matrix.config.release_name }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ runner.workspace }}/${{ matrix.config.release_name }}.tgz
  
