name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          # - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          # - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++", release_name: "cppl-linux-x86_64" }
          - {
            name: "MacOS clang",
            os: macos-10.15, 
            release_name: "cppl-darwin-x86_64",
            final_platform_args: "-DLLVM_ENABLE_LIBCXX -DLLVM_STATIC_LINK_CXX_STDLIB"
            final_build_targets: "cxx cxxabi clang"
            final_check_targets: "check-cxx check-clang"
            final_install_targets: "install-clang install-cxx install-cxxabi"                        
          }
            
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        # ninja version to download. Default: 1.10.0
        version: 1.10.0
    - name: CMake
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=${{ runner.workspace }}/${{ matrix.config.release_name }} \
              -DLLVM_ENABLE_PROJECTS="clang;cppl" \
              {{ matrix.config.final_platform_args }} \ 
              -G "Ninja" ${{ runner.workspace }}/cppl/llvm
    - name: Sources Archive 
      run: |
        tar pczf \
            ${{ runner.workspace }}/${{ matrix.config.release_name }}-src.tgz \
            -C ${{ runner.workspace }} cppl
    - name: Upload Source Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{ matrix.config.release_name }}-src
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ runner.workspace }}/${{ matrix.config.release_name }}-src.tgz
            
    - name: Build
      run: ninja -j4 {{ matrix.config.final_build_targets }}
    - name: Check
      run: ninja -j4 {{ matrix.config.final_check_targets }}
    - name: Install
      run: ninja -j4 {{ matrix.config.final_install_targets }}
      
    - name: Archive 
      run: |
        tar pczf \
            ${{ runner.workspace }}/${{ matrix.config.release_name }}.tgz \
            -C ${{ runner.workspace }} ${{ matrix.config.release_name }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{ matrix.config.release_name }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ runner.workspace }}/${{ matrix.config.release_name }}.tgz
      
