name: C/C++ CI LINT

on:
  push:
    branches: [ levitation-ci-lint ]

jobs: 
  build:

    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          # - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          - { name: "Ubuntu gcc", os: ubuntu-18.04, cc: "gcc", cxx: "g++", release_name: "cppl-linux-x86_64-ci-lint" }
          - { name: "MacOS", os: macos-10.15, bootstrap: false, release_name: "cppl-darwin-x86_64-ci-lint" }

    steps:

    # Install Ninja
    - name: macos.install-ninja
      if: matrix.config.os == 'macos-10.15'
      run: |
        brew install ninja
    - name: linux.install-ninja
      if: matrix.config.os == 'ubuntu-18.04'
      run: sudo apt-get install -y ninja-build

    - name: posix.check-ninja
      if: matrix.config.os != 'windows-latest'
      shell: bash
      run: |
        if [[ "$(which ninja)" == "" ]]; then
          echo "Ninja not found"
          exit 1
        else
          echo "Ninja: $(which ninja)"    
        fi  
      
    # Environment
    - name: Print environment
      if: matrix.config.os != 'windows-latest'
      run: |
        echo "Building with following environment:"
        env

    # Download toolchain (macos only)
    - name: macos.download-clang
      if: matrix.config.os == 'macos-10.15' && !matrix.config.bootstrap
      run: |
        echo wget https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/clang+llvm-9.0.1-x86_64-apple-darwin.tar.xz
        echo tar xvf clang+llvm-9.0.1-x86_64-apple-darwin.tar.xz
    - name: macos.rename-clang
      if: matrix.config.os == 'macos-10.15' && !matrix.config.bootstrap
      run: |
        echo mv clang+llvm-9.0.1-x86_64-apple-darwin ${{ runner.workspace }}/phase1
    - name: macos.xcode-select
      if: matrix.config.os == 'macos-10.15'
      run: |
        sudo xcode-select -s /Library/Developer/CommandLineTools
        echo "Selected Command Line Tools"
        echo "Available SDKs:"
        ls /Library/Developer/CommandLineTools/SDKs
        echo "Following compiler will be used:"
        clang --version
                
    # Checkout sources            
                
    - name: Checkout sources
      uses: actions/checkout@v2        

    # Final phase, run cmake

    - name: macos.phase-final.cmake
      if: matrix.config.os == 'macos-10.15'
      run: |
        mkdir -p ${{ runner.workspace }}/build-final
        cd ${{ runner.workspace }}/build-final
        echo cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=${{ runner.workspace }}/${{ matrix.config.release_name }} \
              -DCMAKE_C_COMPILER=${{ runner.workspace }}/phase1/bin/clang \
              -DCMAKE_CXX_COMPILER=${{ runner.workspace }}/phase1/bin/clang++ \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 \
              -DLEVITATION_DEFAULT_LINKER_VERSION=261 \
              -DLEVITATION_DEFAULT_INCLUDES=/Library/Developer/CommandLineTools/usr/include/c++/v1 \
              -DDEFAULT_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk \
              -DLLVM_ENABLE_PROJECTS="clang" \
              -G "Ninja" ${{ runner.workspace }}/cppl/llvm

    - name: linux.phase-final.cmake
      if: matrix.config.os == 'ubuntu-18.04'
      run: |
        mkdir -p ${{ runner.workspace }}/build-final
        cd ${{ runner.workspace }}/build-final
        echo cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=${{ runner.workspace }}/${{ matrix.config.release_name }} \
              -DLLVM_ENABLE_PROJECTS="clang" \
              -G "Ninja" ${{ runner.workspace }}/cppl/llvm

# Uncomment lines below if you want to build libcxx as well
#     - name: macos.phase-final.build-cxx
#       if: matrix.config.os == 'macos-10.15'
#       run: |
#         cd ${{ runner.workspace }}/build-final
#         ninja -j4 cxxabi cxx

    # Final phase, run build

    - name: phase-final.build-clang
      if: matrix.config.os == 'macos-10.15' || matrix.config.os == 'ubuntu-18.04'
      run: |
        cd ${{ runner.workspace }}/build-final
        # Do nothing


# Uncomment lines below if you want to check for build directory contents.
#     - name: Archive build files
#       if: matrix.config.os == 'macos-10.15'
#       run: |
#         cd ${{ runner.workspace }}
#         tar pczf \
#             ${{ runner.workspace }}/build-final.tgz \
#             ${{ runner.workspace }}/build-final
#          
#     - name: Upload a Build Files Artifact
#       if: matrix.config.os == 'macos-10.15'
#       uses: actions/upload-artifact@v2
#       with:
#         # Artifact name
#         name: build-final
#         # A file, directory or wildcard pattern that describes what to upload
#         path: ${{ runner.workspace }}/build-final.tgz

    # Final phase, run install

    - name: phase-final.install
      if: matrix.config.os == 'macos-10.15' || matrix.config.os == 'ubuntu-18.04'
      run: |
        cd ${{ runner.workspace }}/build-final
        # ninja -j4 install
        mkdir -p ${{ runner.workspace }}/${{ matrix.config.release_name }}
        touch ${{ runner.workspace }}/${{ matrix.config.release_name }}/test.a

    # Final phase, create artifact 

    - name: Archive installation
      if: matrix.config.os == 'macos-10.15' || matrix.config.os == 'ubuntu-18.04'
      run: |
        tar pczf \
            ${{ runner.workspace }}/${{ matrix.config.release_name }}.tgz \
            -C ${{ runner.workspace }} ${{ matrix.config.release_name }}

    - name: Upload installation artifact
      if: matrix.config.os == 'macos-10.15' || matrix.config.os == 'ubuntu-18.04'
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{ matrix.config.release_name }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ runner.workspace }}/${{ matrix.config.release_name }}.tgz
        
    # Final phase, check
      
    - name: Check
      if: matrix.config.os == 'macos-10.15' || matrix.config.os == 'ubuntu-18.04'
      run: |
        cd ${{ runner.workspace }}/build-final
        # ninja -j4 check-clang

  # Idea token from this post:
  # https://github.com/actions/upload-release-asset/issues/28#issuecomment-617208601
  release:
    runs-on: ubuntu-latest
    needs: build
    name: Create a release
    steps:
    - name: Print github.ref
      run: |
        echo ${{ github.ref }}

    - name: Create release on github
      if: startsWith(github.ref, 'refs/tags/levitation-')
      run: |
        set -x
        assets=()
        for asset in ${{ runner.workspace }}/*.tgz; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
